# Generated by Django 5.0 on 2023-12-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainForum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursed_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.TextField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
