# Generated by Django 5.0 on 2024-01-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainForum', '0002_cursed_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghost',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
    ]
