# Generated by Django 5.0 on 2024-01-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainForum', '0003_ghost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghost',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
