# Generated by Django 5.0 on 2024-01-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainForum', '0004_alter_ghost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghost',
            name='category',
            field=models.ForeignKey(choices=[(1, 'Сложные'), (2, 'Средние'), (3, 'Легкие')], default=3, on_delete=django.db.models.deletion.PROTECT, to='MainForum.ghost_category'),
        ),
    ]
