# Generated by Django 5.0 on 2024-01-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainForum', '0005_alter_ghost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGhost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ghost',
            name='category',
            field=models.ForeignKey(choices=[(1, 'Сложные'), (2, 'Средние'), (3, 'Легкие')], default=3, on_delete=django.db.models.deletion.PROTECT, related_name='ghosts', to='MainForum.ghost_category'),
        ),
        migrations.AddField(
            model_name='ghost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='MainForum.tagghost'),
        ),
    ]
